### ISSUE TITLE
Biggest bet on the river card is being carried over to the next round.

### ISSUE THREAD

**Issue by golisai** [atulmahamuni/poker#23]

**Comment by atulmahamuni** [comment]
I think this is a known issue, and there was a PR in the original repo: https://github.com/geobalas/Poker/pull/6
You may want to take a look at this...

**Comment by ilog** [comment]
Not sure why the other PR is not merged yet, its 5 year old. The PR has a same fix as in the PR that I submitted (in a different function though).
