### ISSUE TITLE
Auto fold when exceeds time out

### ISSUE THREAD

**Issue by rvidhun** [atulmahamuni/poker#26]
Auto fold when user not responding. Add timeout of 2-5mins configurable

**Comment by avaidun** [comment]
would be good to have an option to say hold (not fold). especially if the player needs to step out to take a call or something. i.e. hold. someone might have a great hand and needed to step aside to handle something urgent.

**Comment by atulmahamuni** [comment]
Planning to implement this:
If the player does not act for 30 seconds, then:
    if there is no raise prior to the player, their hand will automatically 'check'
    if there is a raise prior to this player's turn to act, their hand will automatically 'fold'
Out of respect for other players, no one player will be able to hold up the game.

**Comment by atulmahamuni** [comment]
Fixed
