### ISSUE TITLE
Minimum raise should be at least the big blind

### ISSUE THREAD

**Issue by avaidun** [atulmahamuni/poker#28]
In No-Limit Hold'em, the minimum bet is usually the big blind. The minimum raise is going to be the amount of the previous bet or raise called. For example, in a 1/2 nl game, the minimum you can raise before the flop is going to be to make $4... you are calling the $2 blind and then raising $2. If you make it four, the next player to act can raise to a minimum of $6... remember you are only raising $2.

This can get tricky when a player is all-in. Keep in mind that a player can always push his whole stack into the middle in NL, even if his stack is less than what a min-bet or min-raise would be. The question that arises often is whether a shortstack shove reopens the action to an original better.

For example, let's say you are playing NL holden with blinds at 100-200. You are first to act after the flop and you bet 500. A shortstacked player then shoves all-in for 700. Two other players call behind him. Now it's back up to you and you want to reraise. This scenario leads to arguments all of the time and I've seen lots of floor staff get it wrong.

Rules are going to be different from place to place, but under the TDA rules, it does not open up the action again to you unless the shortstacked player's raise is at least a full raise. So in the example I gave, the shortstacked player would have to have made it 1000 for you to be able to reraise when it got back to you.

**Comment by atulmahamuni** [comment]
Fixed
